services:
  - type: web
    name: group-chat-search
    env: node
    plan: free
    region: oregon
    buildCommand: "npm --prefix client install && npm --prefix client run build && npm --prefix server install"
    startCommand: "npm --prefix server start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
